"use strict";

var cmd_or_ctrl = (process.platform === "darwin") ? "cmd" : "ctrl";

exports.menu = {
  "new":   { key: "n", modifiers: cmd_or_ctrl },
  "open":   { key: "o", modifiers: cmd_or_ctrl },
  "save":   { key: "s", modifiers: cmd_or_ctrl },
  "saveas": { key: "s", modifiers: cmd_or_ctrl + "+shift" },
  "print":  { key: "p", modifiers: cmd_or_ctrl + "+shift" },
  "message" : { key: "m", modifiers: cmd_or_ctrl },
  "close":  { key: "w", modifiers: cmd_or_ctrl },
  "quit":   { key: "q", modifiers: cmd_or_ctrl },

  "undo":   { key: "z", modifiers: cmd_or_ctrl },
  "redo":   { key: "z", modifiers: cmd_or_ctrl + "+shift" },
  "selectall":{ key: "a", modifiers: cmd_or_ctrl },
  "cut":    { key: "x", modifiers: cmd_or_ctrl },
  "copy":   { key: "c", modifiers: cmd_or_ctrl },
  "paste":  { key: "v", modifiers: cmd_or_ctrl },
  "paste_clipboard": { key: "v", modifiers: cmd_or_ctrl + "+alt" },
  "duplicate": { key: "d", modifiers: cmd_or_ctrl },
  "undo":   { key: "z", modifiers: cmd_or_ctrl },

  "reselect": { key: String.fromCharCode(10), modifiers: cmd_or_ctrl },
  "clear_console": { key: "l", modifiers: cmd_or_ctrl + "+shift" },
  "tidyup": { key: "y", modifiers: cmd_or_ctrl },
  "cordinspector":   { key: "r", modifiers: cmd_or_ctrl + "+shift" },
  "find":   { key: "f", modifiers: cmd_or_ctrl },
  "findagain":{ key: "g", modifiers: cmd_or_ctrl },
  "editmode": { key: "e", modifiers: cmd_or_ctrl },
  "preferences": { key: (process.platform === "darwin") ? "," : "p",
    modifiers: cmd_or_ctrl },

  "zoomin": { key: "=", modifiers: cmd_or_ctrl },
  "zoomout": { key: "-", modifiers: cmd_or_ctrl },
  "zoomreset": { key: "0", modifiers: cmd_or_ctrl },
  "zoomoptimal": { key: "9", modifiers: cmd_or_ctrl },
  "zoomhoriz": { key: "9", modifiers: cmd_or_ctrl + "+alt" },
  "zoomvert": { key: "9", modifiers: cmd_or_ctrl + "+shift" },
  "fullscreen": { key: (process.platform === "darwin") ? "f" : "F11",
    modifiers: (process.platform === "darwin") ? "cmd+ctrl" : null },

  "object": { key: "1", modifiers: cmd_or_ctrl },
  "msgbox": { key: "2", modifiers: cmd_or_ctrl },
  "number": { key: "3", modifiers: cmd_or_ctrl },
  "symbol": { key: "4", modifiers: cmd_or_ctrl },
  "comment": { key: "5", modifiers: cmd_or_ctrl },
  "dropdown": { key: "6", modifiers: cmd_or_ctrl },
  "bang": { key: "b", modifiers: cmd_or_ctrl + "+shift" },
  "toggle": { key: "t", modifiers: cmd_or_ctrl + "+shift" },
  "number2": { key: "n", modifiers: cmd_or_ctrl + "+shift" },
  "vslider": { key: "v", modifiers: cmd_or_ctrl + "+shift" },
  "hslider": { key: "h", modifiers: cmd_or_ctrl + "+shift" },
  "vradio": { key: "d", modifiers: cmd_or_ctrl + "+shift" },
  "hradio": { key: "i", modifiers: cmd_or_ctrl + "+shift" },
  "vu":     { key: "u", modifiers: cmd_or_ctrl + "+shift" },
  "cnv": { key: "c", modifiers: cmd_or_ctrl + "+shift" },

  "nextwin": { key: "PageDown", modifiers: cmd_or_ctrl },
  "prevwin": { key: "PageUp", modifiers: cmd_or_ctrl },
  "pdwin": { key: "r", modifiers: cmd_or_ctrl },

  "audio_on": { key: "/", modifiers: cmd_or_ctrl },
  "audio_off": { key: ".", modifiers: cmd_or_ctrl },

  "browser": { key: "b", modifiers: cmd_or_ctrl },
  "audio_off": { key: ".", modifiers: cmd_or_ctrl },
  "audio_off": { key: ".", modifiers: cmd_or_ctrl },
  "audio_off": { key: ".", modifiers: cmd_or_ctrl },


  // Webapp shortcuts
  "new_web":   { key: "n", modifiers: cmd_or_ctrl + "+alt"},
  "open_web":   { key: "o", modifiers: cmd_or_ctrl + "+alt"},
  "save_web":   { key: "s", modifiers: cmd_or_ctrl + "+alt" },
  "saveas_web": { key: "s", modifiers: cmd_or_ctrl + "+shift" },
  "print_web":  { key: "p", modifiers: cmd_or_ctrl + "+alt" },
  "message_web" : { key: "m", modifiers: cmd_or_ctrl + "+alt"},
  "close_web":  { key: "w", modifiers: cmd_or_ctrl + "+alt" },

  "undo_web":   { key: "z", modifiers: cmd_or_ctrl + "+alt" },
  "redo_web":   { key: "z", modifiers: cmd_or_ctrl + "+shift+alt" },
  "selectall_web":{ key: "q", modifiers: cmd_or_ctrl + "+shift"},
  "cut_web":    { key: "x", modifiers: cmd_or_ctrl + "+shift" },
  "copy_web":   { key: "c", modifiers: cmd_or_ctrl + "+alt"},
  "paste_web":  { key: "v", modifiers: cmd_or_ctrl + "+alt" },
  "paste_clipboard_web": { key: "g", modifiers: cmd_or_ctrl + "+shift+alt" },
  "duplicate_web": { key: "d", modifiers: cmd_or_ctrl + "+alt" },

  "reselect_web": { key: "q", modifiers: cmd_or_ctrl + "+shift+alt" },
  "clear_console_web": { key: "l", modifiers: cmd_or_ctrl + "+shift+alt" },
  "tidyup_web": { key: "y", modifiers: cmd_or_ctrl + "+alt" },
  "cordinspector_web":   { key: "r", modifiers: cmd_or_ctrl + "+shift+alt" },
  "find_web":   { key: "f", modifiers: cmd_or_ctrl + "+alt"},
  "findagain_web":{ key: "f", modifiers: cmd_or_ctrl + "+shift+alt"},
  "editmode_web": { key: "e", modifiers: cmd_or_ctrl + "+shift+alt" },
  "preferences_web": { key: (process.platform === "darwin") ? "," : "p",
    modifiers: cmd_or_ctrl },

  "zoomin_web": { key: "=", modifiers: cmd_or_ctrl },
  "zoomout_web": { key: "-", modifiers: cmd_or_ctrl },
  "zoomreset_web": { key: "0", modifiers: cmd_or_ctrl },
  "zoomoptimal_web": { key: "9", modifiers: cmd_or_ctrl },
  "zoomhoriz_web": { key: "9", modifiers: cmd_or_ctrl + "+alt" },
  "zoomvert_web": { key: "9", modifiers: cmd_or_ctrl + "+shift" },
  "fullscreen_web": { key: (process.platform === "darwin") ? "f" : "F11",
    modifiers: (process.platform === "darwin") ? "cmd+ctrl" : null },

  "object_web": { key: "1", modifiers: cmd_or_ctrl + "+alt" },
  "msgbox_web": { key: "2", modifiers: cmd_or_ctrl + "+alt" },
  "number_web": { key: "3", modifiers: cmd_or_ctrl + "+alt" },
  "symbol_web": { key: "4", modifiers: cmd_or_ctrl + "+alt" },
  "comment_web": { key: "5", modifiers: cmd_or_ctrl + "+alt" },
  "dropdown_web": { key: "m", modifiers: cmd_or_ctrl + "+shift+alt" },
  "bang_web": { key: "b", modifiers: cmd_or_ctrl + "+shift+alt" },
  "toggle_web": { key: "t", modifiers: cmd_or_ctrl + "+shift+alt" },
  "number2_web": { key: "n", modifiers: cmd_or_ctrl + "+shift+alt" },
  "vslider_web": { key: "v", modifiers: cmd_or_ctrl + "+shift+alt" },
  "hslider_web": { key: "h", modifiers: cmd_or_ctrl + "+shift+alt" },
  "vradio_web": { key: "d", modifiers: cmd_or_ctrl + "+shift+alt" },
  "hradio_web": { key: "i", modifiers: cmd_or_ctrl + "+shift+alt" },
  "vu_web":     { key: "u", modifiers: cmd_or_ctrl + "+shift+alt" },
  "cnv_web": { key: "c", modifiers: cmd_or_ctrl + "+shift+alt" },

  "nextwin_web": { key: "PageDown", modifiers: cmd_or_ctrl + "+alt"},
  "prevwin_web": { key: "PageUp", modifiers: cmd_or_ctrl + "+alt"},
  "pdwin_web": { key: "r", modifiers: cmd_or_ctrl },

  "audio_on_web": { key: "/", modifiers: cmd_or_ctrl + "+alt"},
  "audio_off_web": { key: ".", modifiers: cmd_or_ctrl + "+alt"},

  "browser_web": { key: "b", modifiers: cmd_or_ctrl + "+alt" },

}
